@hayak_api_local = http://127.0.0.1:5000/api
# @hayak_api_local = https://app.hayaksa.com/api
# USERS
# admin@hayaksa.com
# client@hayaksa.com
# scanner@hayaksa.com
# entry@hayaksa.com



### Login #####################################################
# @name auth_login_local
POST {{hayak_api_local}}/auth/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "client@gmail.com",
    "password": "123123"
}
###############################################################




### Get accounts (as client or admin) #########################
GET {{hayak_api_local}}/account/list/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json
###############################################################



### Create new account (as client or admin) ###################
POST {{hayak_api_local}}/account/list/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json

{
    "first_name":"abdul",
    "last_name":"alshehri",
    "mobile":"0568111091",
    "email":"newTets@gmail.com",
    "user_type": 2,
    "password": "l22111@Ds1",
    "client_info": {
        "client_type": 5
    },
    "extra_data": {}
}
###############################################################



### Update account (as client or admin) #######################
PATCH {{hayak_api_local}}/account/details/18/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json

{
    "first_name": "Ahmad updated",
    "last_name": "Omar",
    "email": "ahmad1@gmail.com",
    "mobile": "0501234855",
    "user_type": 2,
    "password": "hayak_123"
}
###############################################################


### Get single accont (as client, staff or admin) #############
GET {{hayak_api_local}}/account/details/18/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json
###############################################################



### Delete account (as client or admin)  ######################
DELETE {{hayak_api_local}}/account/details/18/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json
###############################################################