@hayak_api_local = http://127.0.0.1:8000/api
# @hayak_api_local = https://app.hayaksa.com/api
# USERS
# admin1@gmail.com
# client1@gmail.com
# scanner1@gmail.com
# entry1@gmail.com



### Login ####################################################
# @name auth_login_local
POST {{hayak_api_local}}/auth/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "abdul@gmail.com",
    "password": "123123"
}
##############################################################




### Get cards (as client or admin) #################################
GET {{hayak_api_local}}/billing/card/list/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json
###############################################################



### Create new card (as client or admin) ###################
POST {{hayak_api_local}}/billing/card/list/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json

{
    "payment_method": 1,
    "name": "Abdulwahab Alshehri",
    "expiry_date": "2020-01-09",
    "number": 123131313,
    "cvv": 333
}
###############################################################

### get  card (as client or admin) ###################
GET {{hayak_api_local}}/billing/card/details/12/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json

###############################################################

### update  card (as client or admin) ###################
PATCH {{hayak_api_local}}/billing/card/details/10/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json

{
    "payment_method": 1,
    "name": "Abulwahab Alshehri",
    "expiry_date": "2020-01-09",
    "number":1212,
    "cvv": 111
}
###############################################################

### DELETE  card (as client or admin) ###################
DELETE {{hayak_api_local}}/billing/card/details/12/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json

###############################################################



### Get trans (as client or admin) #################################
GET {{hayak_api_local}}/billing/trans/list/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json
###############################################################



### Create new card (as client or admin) ###################
POST {{hayak_api_local}}/billing/trans/list/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json

{
    "status":1,
    "paid_at": "2023-01-09",
    "total_price":11,
    "product":1,
    "quantity":1,
    "subtotal":1,
    "discunt":1,
    "tax":1
}
###############################################################

### get  card (as client or admin) ###################
GET {{hayak_api_local}}/billing/trans/details/1/ HTTP/1.1
Authorization: Bearer {{auth_login_local.response.body.access}}
Content-Type: application/json

###############################################################

# ### update  card (as client or admin) ###################
# PATCH {{hayak_api_local}}/billing/card/details/10/ HTTP/1.1
# Authorization: Bearer {{auth_login_local.response.body.access}}
# Content-Type: application/json

# {
#     "payment_method": 1,
#     "name": "Abulwahab Alshehri",
#     "expiry_date": "2020-01-09",
#     "number":1212,
#     "cvv": 111
# }
# ###############################################################

# ### DELETE  card (as client or admin) ###################
# DELETE {{hayak_api_local}}/billing/card/details/12/ HTTP/1.1
# Authorization: Bearer {{auth_login_local.response.body.access}}
# Content-Type: application/json

# ###############################################################