# Generated by Django 4.0.2 on 2023-03-01 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_invitation_entries_invitation_invitation_type'),
        ('auth_system', '0006_alter_customuser_user_type'),
        ('account', '0015_remove_invitation_event_delete_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
