# Generated by Django 4.0.2 on 2023-03-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_rename_entries_invitation_tickets'),
        ('account', '0017_remove_scanner_event_scanner_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='events',
            field=models.ManyToManyField(null=True, related_name='scanners', to='event.Event'),
        ),
    ]
