# Generated by Django 4.0.2 on 2023-03-13 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_rename_entries_invitation_tickets'),
        ('auth_system', '0007_alter_customuser_mobile'),
        ('account', '0018_alter_scanner_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regular',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='is_data_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_scanner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('events', models.ManyToManyField(null=True, related_name='dataEntry', to='event.Event')),
            ],
        ),
    ]
