# Generated by Django 4.0.2 on 2023-03-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_regular_client_is_data_entry_client_is_regular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.client'),
        ),
        migrations.AlterField(
            model_name='regular',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.client'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.client'),
        ),
    ]
