# Generated by Django 4.0.2 on 2022-12-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventtype_alter_event_location_alter_event_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='first_name',
        ),
    ]
