# Generated by Django 4.0.2 on 2022-12-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='title',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='title',
            name='title_en',
        ),
        migrations.AddField(
            model_name='invitation',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.title'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviations', to='event.event'),
        ),
    ]
