# Generated by Django 4.0.2 on 2022-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_invitation_nickname_remove_title_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
