# Generated by Django 4.0.2 on 2022-12-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='name_en',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='name_ar',
            new_name='label_ar',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
