# Generated by Django 4.0.2 on 2022-12-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_invitationstatus_remove_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.invitationstatus'),
        ),
    ]
