# Generated by Django 4.0.2 on 2023-01-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrs'),
        ),
    ]
