# Generated by Django 4.0.2 on 2023-01-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_invitation_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(blank=True, default='Abdullah Mohammed', max_length=500, null=True),
        ),
    ]
