# Generated by Django 4.0.2 on 2023-01-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_invitation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation',
            field=models.ImageField(blank=True, null=True, upload_to='invitations'),
        ),
    ]
