# Generated by Django 4.0.2 on 2023-01-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_invitation_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='rank',
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('guest', 'guest'), ('vip', 'vip'), ('management', 'management'), ('participant', 'participant'), ('organizer', 'organizer'), ('media', 'media'), ('instructor', 'instructor')], default='participant', max_length=256),
        ),
    ]
