# Generated by Django 4.0.2 on 2023-02-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_invitation_email_alter_invitation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='title',
        ),
    ]
