# Generated by Django 4.0.2 on 2023-02-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_remove_invitation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.title'),
        ),
    ]
