# Generated by Django 4.0.2 on 2023-02-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_invitation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
