# Generated by Django 4.0.2 on 2023-02-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_remove_invitation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
