# Generated by Django 4.0.2 on 2023-02-14 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
