# Generated by Django 4.0.2 on 2023-02-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_invitation_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
