# Generated by Django 4.0.2 on 2023-03-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='entries',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(blank=True, default='no type', max_length=1000, null=True),
        ),
    ]
