# Generated by Django 4.0.2 on 2023-07-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_alter_invitation_invitation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitation_type',
        ),
    ]
