# Generated by Django 4.0.2 on 2023-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_remove_invitation_invitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(blank=True, default='no type', max_length=1000, null=True),
        ),
    ]
