# Generated by Django 4.0.2 on 2023-04-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_invitation_added_by'),
        ('settings', '0002_staffeventsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_tickets_per_qr', models.BooleanField(default=True)),
                ('entries_per_qr', models.PositiveSmallIntegerField(choices=[(1, 'Single entry'), (2, 'Multiple entries')], default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('ticket_type', models.ManyToManyField(to='settings.TicketType')),
                ('zones', models.ManyToManyField(to='settings.Zones')),
            ],
        ),
    ]
