# Generated by Django 4.0.2 on 2023-01-28 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_invitation_email_alter_invitation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='event',
        ),
        migrations.AddField(
            model_name='scan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scan',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.invitation'),
        ),
    ]
